branches:
  only:
      - master
      - code_refactor_2020.01

matrix:
  fast_finish: true
  include:
    - language: java
      jdk: openjdk8
      os: linux
      sudo: required

    - language: java
      jdk: openjdk9
      os: linux
      sudo: required

    - language: java
      jdk: openjdk10
      os: linux
      sudo: required

    - language: java
      jdk: openjdk11
      os: linux
      sudo: required

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: 
  - chmod +x gradlew
  - gradlew test bootJar
